"""Final compact output schema."""

FINAL_COLUMNS = [
    "patent_id",
    "patent_id_us",
    "paper_id",
    "work_doi",
    "pair_id",
    "pair_source",
    "author_team_size",
    "inventor_team_size",
    "team_size_difference",
    "multiple_assignee",
    "multiple_author_institution",
    "assignee_type_company",
    "assignee_type_company_list",
    "assignee_type_university",
    "assignee_type_university_list",
    "author_type",
    "journal_impact",
    "word_overlap_score",
    "semantic_similarity_score",
    "citation_overlap_score",
    "previous_experience",
    "previous_experience_first_last",
    "primary_topic_display_name",
    "primary_subfield_display_name",
    "primary_field_display_name",
    "primary_domain_display_name",
    "wipo_fields",
    "ipc_codes",
    "ipc_sectors",
    "international_collab",
    "geographical_distance",
    "publication_year",
    "patent_priority_year",
    "earliest_patent_year",
    "lag_days",
    "mean_age_of_work_references",
    "mean_age_of_patent_references",
    "work_reference_cited_by_counts_mean",
    "patent_reference_cited_by_counts_mean",
    "work_reference_list_length",
    "patent_reference_list_length",
    "uspto_non_patent_ref",
    "uspto_patent_citation",
    "patent_num_claims",
    "patent_first_claim_length",
]


RENAME_MAP = {
    "relative_filing_date": "lag_days",
    "avg_haversine_km": "geographical_distance",
    "work_reference_age_days_mean": "mean_age_of_work_references",
    "patent_reference_age_days_mean": "mean_age_of_patent_references",
    "num_work_references": "work_reference_list_length",
    "patent_num_references": "patent_reference_list_length",
}
